### ISSUE TITLE
How to use onEnter() with child Components for fetching data on the Server Side

### ISSUE THREAD

**Issue by kotgakapainor** [nightwolfz/inferno-starter#28]
My understanding of onEnter is, that it will only run on Router Components. Is it possible to use it with childs further down the tree? I'd like to fetch some Icons and json data on the server side for SEO goodness.
When implementing onEnter in my Icon Component it will not be invoked.

````
// class Icon ...
static onEnter(props) {
        return props.data.getIcon(props.icon, props.color)
    }

// data Store..
@action async getIcon(slug, color) {
        const res = await request.get(`/icons/${slug}.svg`, 'svg')
        const colloredRes = await res.replace('fill="#000000"', 'fill="#' + color + '"')
        return runInAction(() => {
                this.icons.set(slug, colloredRes)
            })
      }
````
I'm using your request.js of the _next_-Tree

I assume manipulating the `renderProps` in `server/middleware/render.js` would be the right way?

An equivalent in function would be [React Async Component](https://github.com/ctrlplusb/react-async-component) but i'm afraid my knowledge is to limited for porting a library to inferno. Also I dislike inferno-compat because of performance- and size-sake (Or am I mistaken here?) .

What would you recommend?

**Comment by nightwolfz** [comment]
Hey @kotgakapainor!

Well it's definitely not an easy task, I've tried to do something similar in the past but it always ended up being way over-complicated. The problem is with finding the `onEnter` static method.

With the routes, it's pretty easy to know where to look but once you're talking about components inside components, you would have to "render" them first because of conditional rendering etc to get the static methods and render them again a second time so that your newly fetched data is applied.

Another solution could be converting [react-tree-walker](https://github.com/ctrlplusb/react-tree-walker) to inferno, which hopefully shouldn't take more than an hour (it seems pretty straight forward) and use that to execute your onEnter methods.

Hope that helps!
