### ISSUE TITLE
How to swap out internal API with external API

### ISSUE THREAD

**Issue by dav-is** [nightwolfz/inferno-starter#31]
I’m using a different language to host our API. I ripped out mongo and the models and such but I’m not sure how to go about [this]( https://github.com/nightwolfz/inferno-starter/blob/master/server/middleware/context.js#L21). Should I fetch the account after initializing the stores as the method to do so is stored in there?

I’m also confused about what and the difference between a state and store are.

To be clear, this is a question. Not an issue.

**Comment by nightwolfz** [comment]
@dav-is 

> Should I fetch the account after initializing the stores as the method to do so is stored in there?

1. Initialize the empty state with the defaults ([example](https://github.com/nightwolfz/inferno-starter/blob/master/server/middleware/context.js#L9))
2. Fetch your account/session data
3. Update the state before injecting into your HTML.

> I’m also confused about what and the difference between a state and store are.

State contains the state of your application (ex: list of your todos, UI state etc).
Stores contain the methods that mutate that state (ex: adding a todo, fetching data).
Technically our State object is also a store, but we make the differentiation so that our logic is easier to follow by using the same principes as redux (one big state object).
